export const profile = {
  name: 'Aman Jaiswal',
  initials: 'AJ',
  role: 'AI/ML Engineer · Web Developer',
  location: 'Ranchi, Jharkhand, India',
  timezone: 'UTC+5:30',
  email: 'aerraj50@gmail.com',
  phone: '',
  status: 'Available for new opportunities',
  bio: "AI/ML engineer from India building production-grade systems across multilingual speech, retrieval-augmented generation, and applied research. Currently researching Indic-language ASR at IIT Ropar with the Annam.ai consortium.",
  shortBio: "AI/ML engineer building AI that ships — research through production.",
  socials: {
    github: 'https://github.com/amanraj74',
    linkedin: 'https://www.linkedin.com/in/aman-jaiswal-05b962212/',
    twitter: '',
    scholar: '',
  },
  resumeUrl: './resume.pdf',
};

export const stats = [
  { num: 2, suffix: '×', label: 'National Winner', detail: 'IISc · IIT BHU' },
  { num: 4, suffix: '×', label: 'IIT Hackathon Finalist', detail: 'Top-10 Shaastra' },
  { num: 2, suffix: '×', label: 'Research Intern', detail: 'IIT Ropar · NIT Kurukshetra' },
  { num: 22, suffix: '+', label: 'Indic Languages Modeled' },
];

export const capabilities = [
  {
    title: 'Applied ML',
    description: 'Tabular, classification, and forecasting models with calibrated evaluation.',
    tags: ['scikit-learn', 'XGBoost', 'Pandas'],
    icon: 'cube',
  },
  {
    title: 'Deep Learning',
    description: 'Transformers, signal models, and training pipelines that survive noisy data.',
    tags: ['PyTorch', 'HuggingFace', 'LoRA'],
    icon: 'brain',
  },
  {
    title: 'NLP & Speech',
    description: 'Multilingual ASR, semantic retrieval, and conversational AI for low-resource Indic languages.',
    tags: ['Sentence-BERT', 'FAISS', 'MFCC'],
    icon: 'mic',
  },
  {
    title: 'Generative AI',
    description: 'RAG systems with citation, lightweight fine-tuning, and production-grade assistants.',
    tags: ['LangChain', 'RAG', 'LoRA'],
    icon: 'sparkles',
  },
  {
    title: 'Engineering',
    description: 'Models that ship — FastAPI services, Docker, clean Python, version control.',
    tags: ['FastAPI', 'Docker', 'Git'],
    icon: 'terminal',
  },
  {
    title: 'Web Frontend',
    description: 'Interfaces that respect users — semantic HTML, accessible defaults, motion with intent.',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
    icon: 'code',
  },
];

export const projects = [
  {
    id: 'eeg',
    title: 'EEG Emotion Recognition',
    year: '2026',
    tag: 'Deep Learning · Signal Processing',
    description: 'EEG-based emotion classification across three dimensions (Arousal, Valence, Dominance) using the DREAMER dataset — 414 trials, 14 channels, 23 subjects. Best result: 63.86% Arousal accuracy via ensemble voting. Top-10 finalist at Shaastra 2026, IIT Madras (NeuroHack) among 1,000+ teams.',
    tech: ['Python', 'MNE-Python', 'scikit-learn', 'Signal Processing'],
    href: 'https://github.com/amanraj74/Neurohack',
    gradient: 'g1',
    mark: 'EEG',
  },
  {
    id: 'arbitrage',
    title: 'Cross-Asset Portfolio Optimization',
    year: '2025',
    tag: 'Quant Finance · Winner',
    description: 'Winner project at Arbitrage Arena 2025 (IISc Bangalore). Mean-Variance Optimization (Markowitz) over 12 assets across equities, indices, commodities, and crypto over 6.3 years. Best portfolio: 1.458 Sharpe ratio, 28.63% annualized return, 388.77% total return with -32.37% max drawdown.',
    tech: ['Python', 'NumPy', 'Pandas', 'SciPy'],
    href: 'https://github.com/amanraj74/Arbitrage-Arena-2025-IISc-Bangalore',
    gradient: 'g10',
    mark: 'PA',
  },
  {
    id: 'intelliflow',
    title: 'IntelliFlow — Logistics AI Copilot',
    year: '2025',
    tag: 'GenAI · Real-time · Finalist',
    description: 'Real-time logistics intelligence copilot for the Pathway × Iota Cluster IIT Ropar GenAI Hackathon. Watches data/streams/ with Pathway, runs a RAG pipeline over live embeddings, orchestrates multi-agent anomaly/risk detection, and ships behind FastAPI + Streamlit + Docker. Live queries return updated answers within ~3 seconds of new data arriving.',
    tech: ['Pathway', 'FastAPI', 'Streamlit', 'Docker'],
    href: 'https://github.com/amanraj74/IntelliFlow-Logistics-AI-Copilot-New',
    gradient: 'g4',
    mark: 'IF',
  },
  {
    id: 'deepguard',
    title: 'DeepGuard AI — Deepfake Detection',
    year: '2026',
    tag: 'Cybersecurity · Vision Transformer',
    description: 'Real-time deepfake and AI-generated media detector. Runs 30 inference passes per image (2 ViT models × 5 augmentations × 3 face-crop scales) with MTCNN face detection, pixel-level forensics, and a FastAPI + Streamlit stack. Built for IIT Bombay Hack & Break 2026 (Generative AI & Cybersecurity).',
    tech: ['PyTorch', 'FastAPI', 'Streamlit', 'ViT'],
    href: 'https://github.com/amanraj74/DeepGuard-AI',
    gradient: 'g9',
    mark: 'DG',
  },
  {
    id: 'retrieval',
    title: 'KnowMap — Semantic Search & Knowledge Graph',
    year: '2025',
    tag: 'Semantic Search · Knowledge Graphs',
    description: 'Built for the Infosys Springboard KnowMap platform. Embedding-based document search using sentence-transformers, RDF/Turtle knowledge graph with RDFLib, rule-based inference engine (subfield → parent concept), and an interactive D3.js visualization layer. <100ms search latency across thousands of documents.',
    tech: ['sentence-transformers', 'RDFLib', 'spaCy', 'Python'],
    href: 'https://github.com/amanraj74/Semantic-Search-Visualization',
    gradient: 'g3',
    mark: 'KM',
  },
  {
    id: 'quadruped',
    title: 'Quadruped Autonomous Navigation',
    year: '2025',
    tag: 'Robotics · ROS2',
    description: 'ROS2 control stack for the TurtleBot3/Spot platform — implements square-path (2m × 2m, 100% accuracy), circular-path (r=1.5m), and an autonomous navigation mode with multi-zone LiDAR obstacle detection, adaptive speed control, and stuck-recovery state machine. Completed finals at IIT Bhubaneswar Quadruped Challenge 2025.',
    tech: ['ROS2', 'Python', 'Gazebo', 'LiDAR'],
    href: 'https://github.com/amanraj74/Quadruped-Challenge-IIT-Bhubaneswar',
    gradient: 'g6',
    mark: 'QP',
  },
  {
    id: 'bharattrend',
    title: 'BharatTrend Analytics',
    year: '2025',
    tag: 'Market Analytics · Streamlit',
    description: 'AI-powered e-commerce market analysis and price prediction for Indian markets. Analyzes 13,950+ products from Flipkart & Amazon across 244 categories and 500+ cities, achieving 97.46% accuracy with an ensemble of Random Forest, K-Means, and Linear Regression. Ships with an interactive 5-tab Streamlit dashboard.',
    tech: ['Python', 'Streamlit', 'scikit-learn', 'Random Forest'],
    href: 'https://github.com/amanraj74/BharatTrend-Analytics',
    gradient: 'g8',
    mark: 'BT',
  },
  {
    id: 'stock',
    title: 'Stock Price Predictor',
    year: '2025',
    tag: 'ML · Forecasting',
    description: 'Forecasting stock movements using historical price data, engineered features, and regression-based ML models. Built during AI internship at Codec Technologies.',
    tech: ['Python', 'scikit-learn', 'Pandas'],
    href: 'https://lnkd.in/gta7DWsA',
    gradient: 'g7',
    mark: 'STK',
  },
  ];

export const experience = [
  {
    period: 'Jul 2025 — Jan 2026',
    role: 'AI Research Intern',
    org: 'IIT Ropar · Annam.ai',
    desc: 'Conducted large-scale ASR experiments across 22+ Indic languages, including low-resource dialects. Designed multilingual speech datasets, fine-tuned transformer-based acoustic models, and shipped inference pipelines behind FastAPI microservices for downstream research teams.',
    highlights: ['22+ languages', 'Multilingual ASR', 'FastAPI microservices'],
    featured: true,
  },
  {
    period: 'Jun — Jul 2026',
    role: 'BSERC Intern',
    projectTitle: 'OSCAR — AI-Based Military Intelligence & Threat Analysis Dashboard',
    org: 'Bharat Space Education Research Centre',
    desc: 'Designed and shipped an open-source AI/ML dashboard for military intelligence and threat analysis across 50+ countries.',
    bullets: [
      'Architected and shipped OSCAR, an open-source OSINT dashboard that fuses GDELT global events, NewsAPI, Reddit, weather, and markets into a 10-page interactive Streamlit UI for defense-relevant threat analysis across 50+ countries.',
      'Built an 8-layer data pipeline (ingestion → silver → NLP → ML) with 7 source-specific scrapers, Pydantic v2 validation, spaCy NER, DistilBERT sentiment, XGBoost-based escalation classifier (3 horizons), Prophet forecaster, and Isolation Forest anomaly detector.',
      'Delivered as a production-grade release: 213 tests passing, 68% coverage, ruff/black/mypy clean, multi-stage Docker image, full model registry with MLflow tracking. MIT-licensed and live on GitHub.',
    ],
    highlights: ['OSCAR dashboard', 'GDELT + 7 sources', '213 tests passing'],
  },
  {
    period: 'May 2026 — Present',
    role: 'Summer Research Intern',
    org: 'National Institute of Technology, Kurukshetra',
    desc: 'Research in NLP, model training, and optimization. Built evaluation harnesses for reproducibility, profiled training runs to reduce GPU-hours, and prototyped lightweight fine-tuning recipes (LoRA / prefix-tuning) on top of open-source LLMs.',
    highlights: ['Reproducibility', 'Training optimization', 'LoRA fine-tuning'],
  },
  {
    period: 'May — Jul 2026',
    role: 'Open Source Contributor',
    org: 'GirlScript Summer of Code 2026',
    desc: 'Contributed to real-world open-source projects across the Open Source and AI/Agents tracks. Built intelligent systems end-to-end and collaborated with maintainers and the wider community.',
    highlights: ['OSS contributions', 'AI/Agents track', 'Community'],
  },
  {
    period: 'Jan 2026 — Jun 2026',
    role: 'Assistance Partner Apprentice (on-site)',
    org: 'Kotak Life',
    desc: 'Apprenticeship exploring AI applications in insurance and financial services. Working with product, data, and engineering teams to understand how regulated industries adopt ML-driven workflows.',
    highlights: ['Insurance domain', 'On-site', 'Cross-functional'],
  },
  {
    period: 'Jan — Mar 2026',
    role: 'AI/ML Intern',
    org: 'HEProAI',
    desc: 'Worked across NLP and applied ML pipelines, translating research prototypes into shippable APIs. Implemented data preprocessing, model evaluation, and integration with backend services; collaborated with senior engineers on production deployments.',
    highlights: ['NLP pipelines', 'Production deployment', 'Backend integration'],
  },
  {
    period: '2025',
    role: 'Infosys Springboard Intern',
    org: 'KnowMap Platform · Infosys',
    desc: 'Built the KnowMap semantic-search module: sentence-transformer embeddings, RDF/Turtle knowledge graph with RDFLib, rule-based inference engine, and an interactive D3.js visualization layer. Designed JWT-based auth and RBAC, structured data pipelines for knowledge-graph ingestion, and shipped production endpoints with proper error handling and audit logging.',
    highlights: ['JWT auth', 'RDF knowledge graphs', 'sentence-transformers'],
  },
  {
    period: 'Jun — Jul 2025',
    role: 'AI Intern',
    org: 'Codec Technologies (AICTE & ICAC Certified)',
    desc: 'Completed a one-month intensive AICTE & ICAC certified program. Shipped two production-style ML projects end-to-end: a Stock Price Predictor (regression with engineered features) and a Twitter Sentiment Analysis system (NLP pipeline with model evaluation).',
    highlights: ['2 shipped projects', 'ML + NLP', 'AICTE & ICAC certified'],
  },
];

export const achievements = [
  { icon: '🏆', title: 'Top 10 — Shaastra 2026, IIT Madras', desc: 'NeuroHack Challenge among 1,000+ teams' },
  { icon: '🥈', title: 'Top 25 — IIT Patna × Jilo Health', desc: 'VaaniCare — Indic Voice AI Healthcare' },
  { icon: '🎓', title: 'Google Student Ambassador', desc: 'Selected to drive AI awareness on campus' },
  { icon: '🤖', title: 'IIT Bhubaneswar Quadruped Finalist', desc: 'ROS2 autonomous navigation challenge' },
  { icon: '🚀', title: 'IntelliFlow — GenAI Hackathon', desc: 'Pathway × Iota Cluster · 1,800+ teams' },
  { icon: '☁️', title: 'Google Cloud Arcade — Legend', desc: 'All labs complete · 2025 Season 2' },
  { icon: '🌟', title: 'GSSOC 2026 Contributor', desc: 'Open Source & AI/Agents track' },
  { icon: '📚', title: 'AI Sprint Bootcamp 2025', desc: 'HelloPM graduate' },
];

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Work', href: '/projects' },
  { label: 'Resume', href: '/resume' },
  { label: 'Contact', href: '/contact' },
];